import "./globals.css";
import { Inter } from "next/font/google";
import Header from "../components/header";
import Cursor from "@/components/cursor/cursor";
import Portfolio from "@/components/portfolio/Portfolio";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Cursor />
        <Header />
        <Portfolio />
        {children}
      </body>
    </html>
  );
}
